import {
  Wrench,
  Smartphone,
  RotateCcw,
  HandHeart,
  Cpu,
  PhoneCall,
  Wifi,
  GraduationCap
} from 'lucide-react';

import { HeroSlide, PromoTile, FooterColumn } from './types';

import { BrandDataType, ProductDataType, SustainabilityCardProps } from '@/modules/homePage/homePage.types';


export const FOOTER_DATA: FooterColumn[] = [
  {
    title: 'HELP & SUPPORT',
    links: [
      { label: 'Help & Support', href: '#' },
      { label: 'Track my order', href: '#' },
      { label: 'Faulty goods returns', href: '#' },
      { label: 'Refunds & Warranties guide', href: '#' },
      { label: 'Advertised offers', href: '#' },
      { label: 'Advertising corrections', href: '#' },
      { label: 'Scam alerts', href: '#' },
      { label: 'Product recalls', href: '#' },
    ],
  },
  {
    title: 'NEWS & REVIEWS',
    links: [
      { label: 'News & Reviews', href: '#' },
      { label: 'Latest Tech', href: '#' },
      { label: 'Competitions', href: '#' },
      { label: 'Guides & Tips', href: '#' },
      { label: 'Reviews', href: '#' },
      { label: 'Latest STACK magazine', href: '#' },
      { label: 'Previous STACK editions', href: '#' },
    ],
  },
  {
    title: 'COMPANY',
    links: [
      { label: 'About us', href: '#' },
      { label: 'Careers', href: '#' },
      { label: 'Sustainability', href: '#' },
      { label: 'Helping Hands', href: '#' },
      { label: 'Investor information', href: '#' },
      { label: 'BYOD Portal', href: '#' },
      { label: 'JB Hi-Fi Business', href: '#' },
      { label: 'JB Hi-Fi Marketplace', href: '#' },
      { label: 'Join JB Perks', href: '#' },
    ],
  },
];

export const PAYMENT_METHODS = [
  { name: 'JB Gift Card', image: 'https://images.ctfassets.net/xa93kvziwaye/78wchNRvDtNgjqdzDgHv35/903631f459d13bcfced2f95dc7cd052d/icon_gift_card_2x.webp' },
  { name: 'Mastercard', image: 'https://images.ctfassets.net/xa93kvziwaye/4d3Hyp4oWSbJQOfMr6D47v/b5421421b512ae2f6d0cfafbfb646dac/mastercard-icon.svg' },
  { name: 'Visa', image: 'https://images.ctfassets.net/xa93kvziwaye/5ugyedMGaUnjqxRLxgan5M/4f9e5f2c569779b29316feca41dc45e4/visa-icon.svg' },
  { name: 'PayPal', image: 'https://images.ctfassets.net/xa93kvziwaye/3cPPxiWLnkXEtXKia4V1cq/955a681e5ee05e4a64c81976c7e1e181/paypal-mark-color_2025.svg' },
  { name: 'Apple Pay', image: 'https://images.ctfassets.net/xa93kvziwaye/3ance90UoG9fhsRuGOaqf6/8eec91fbe530b9d0401eb70e05e5a72c/apple_pay_2x.webp' },
  { name: 'Amex', image: 'https://images.ctfassets.net/xa93kvziwaye/6goAHlPjJFdALlVXCblIiZ/35216910a9e692bac7ac8fb0470b7043/amex.svg' },
  { name: 'Afterpay', image: 'https://images.ctfassets.net/xa93kvziwaye/3n9v2y74dLbbyHdrLnKu6M/5f61491657140324beac2ad2411793f5/afterpay_lockup_blackonmint_2x.webp' },
  { name: 'Zip', image: 'https://images.ctfassets.net/xa93kvziwaye/6Wca3Ypbnw3iylu6Psygl6/ad543638070985e7c529f801b8a058a3/zippay.svg' },
  { name: 'Latitude', image: 'https://images.ctfassets.net/xa93kvziwaye/61ZdGs6RAwjTEE97FXPkoo/6cc6e260f1ee3046a67e8802d45083e5/Latitude2026-logo.svg' },
  { name: 'UnionPay', image: 'https://images.ctfassets.net/xa93kvziwaye/6V60oPKVhubX1xwljxlzVD/41aae813cd93256b0c5f2b0a06160a90/Union-Pay-logo.png' },
];

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: 'slide-1',
    title: 'TAX TIME MADNESS',
    subtitle: 'MASSIVE SAVINGS ON THE BIGGEST TECH BRANDS! LAPTOPS, TVS, PHONES & MORE.',
    ctaText: 'SHOP THE SALE',
    ctaLink: '#',
    image: '/h1.webp',
    bgColor: 'bg-red-600',
    textColor: 'text-white',
    badge: 'MEGA DEAL'
  },
  {
    id: 'slide-2',
    title: 'UP TO $500 OFF OLED TVS',
    subtitle: 'Experience breathtaking picture quality with selected LG, Samsung and Sony OLED TVs.',
    ctaText: 'VIEW OLED DEALS',
    ctaLink: '#',
    image: '/h2.webp',
    bgColor: 'bg-zinc-900',
    textColor: 'text-white',
    badge: 'TICKET PRICE'
  },
  {
    id: 'slide-3',
    title: 'BACK TO WORK SPECIALS',
    subtitle: 'Upgrade your home office with blazing fast laptops, monitors and printers from $299.',
    ctaText: 'COMPUTERS & MORE',
    ctaLink: '#',
    image: '/h3.webp',
    bgColor: 'bg-yellow-400',
    textColor: 'text-black',
    badge: 'PERKS EXCLUSIVE'
  }
];

export const PROMO_TILES: PromoTile[] = [
  {
    id: 'promo-1',
    title: 'Samsung Galaxy S24 Series',
    subtitle: 'Get a bonus JB Hi-Fi Gift Card worth up to $250 with selected models.',
    ctaText: 'Shop S24',
    ctaLink: '#',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80',
    bgColor: 'bg-blue-900',
    textColor: 'text-white'
  },
  {
    id: 'promo-2',
    title: 'Gaming Gear Frenzy',
    subtitle: 'Save on PS5 Consoles, Switch OLED and hot game titles. Online & In-Store.',
    ctaText: 'Browse Gaming',
    ctaLink: '#',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=600&q=80',
    bgColor: 'bg-purple-950',
    textColor: 'text-white'
  },
  {
    id: 'promo-3',
    title: 'Dyson Airwrap Specials',
    subtitle: 'Ticket price drop on hair styling, cordless vacuums and air purifiers.',
    ctaText: 'Shop Dyson',
    ctaLink: '#',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    bgColor: 'bg-pink-900',
    textColor: 'text-white'
  },
  {
    id: 'promo-4',
    title: 'Smart Home Security',
    subtitle: 'Keep your home safe. Up to 30% off Ring, Eufy, and Google Nest cameras.',
    ctaText: 'Get Secured',
    ctaLink: '#',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80',
    bgColor: 'bg-zinc-800',
    textColor: 'text-white'
  }
];

export const CIRCLE_CATEGORIES = [
  { id: 1, name: 'Movies & TV Shows', image: '/c1.webp' },
  { id: 2, name: 'Music & Vinyl', image: '/c2.webp' },
  { id: 3, name: 'Collectibles & Merchandise', image: '/c3.webp' },
  { id: 4, name: 'Outdoors & Travel', image: '/c4.webp' },
  { id: 5, name: 'Cameras & Drones', image: '/c5.webp' },
  { id: 6, name: 'Content Creator Gear', image: '/c6.webp' },
  { id: 7, name: 'Office Supplies', image: '/c7.webp' },
  { id: 8, name: 'Online-only Range', image: '/c8.webp' },
  { id: 9, name: 'Gaming', image: '/c9.webp' },
  { id: 10, name: 'Home Security', image: '/c10.webp' }
];

export const HOT_TABS = [
  'Hottest Deals',
  '40% Off Deals',
  'New at JB - Google Pixel 11 Series',
  'Computers',
  'TVs & Soundbars',
  'Mobile Phones',
  'Home Appliances',
  'Refurbished Tech',
];

export const PRODUCTS = [
  {
    id: 1,
    title: 'Apple iPhone 17 Pro Max 256GB (Silver)',
    image: '/wh1.webp',
    badge: 'TRADE IN YOUR OLD PHONE',
    badgeType: 'outline-red',
    rating: 4.7,
    reviews: 43,
    price: 1899,
    priceTagLabel: 'RED HOT DEAL',
  },
  {
    id: 2,
    title: 'Apple iPhone 17 Pro 256GB (Cosmic Orange)',
    image: '/wh2.webp',
    badge: 'TRADE IN YOUR OLD PHONE',
    badgeType: 'outline-red',
    rating: 4.3,
    reviews: 24,
    price: 1799,
    priceTagLabel: 'RED HOT DEAL',
  },
  {
    id: 3,
    brand: 'HP',
    title: 'HP Laptop 15-fd0943tu 15.6" Full HD Laptop (Intel N150) [128GB]',
    image: '/wh3.webp',
    badge: 'BUNDLE BUY',
    badgeType: 'purple',
    rating: 4.0,
    reviews: 2,
    price: 379,
    priceTagLabel: 'RED HOT DEAL',
  },
  {
    id: 4,
    brand: 'LG',
    title: 'LG 65" OLED EVO AI C6 4K Smart TV [2026]',
    image: '/wh4.webp',
    badge: 'ON SALE',
    secondaryBadge: 'BUNDLE BUY',
    badgeType: 'solid-red',
    rating: 5.0,
    reviews: 4,
    price: 3277,
    originalPrice: 3995,
    savings: '$718 OFF^',
    tagline: 'FREE DELIVERY',
  },
  {
    id: 5,
    brand: 'DREAM',
    title: 'Dream Aqua Roller AE Robot |Vacuum Cleaner',
    image: '/wh5.webp',
    badge: 'ON SALE',
    badgeType: 'solid-red',
    rating: 3.5,
    reviews: 330,
    price: 899,
    originalPrice: 2399,
    savings: '$1500 OFF^',
  },
  {
    id: 6,
    brand: 'DELL',
    title: 'Dell XPS 13 13.4" 2.5K Touch Laptop (Intel Core 5 - 320) [512GB/8GB]',
    image: '/wh6.webp',
    badge: 'ON SALE',
    secondaryBadge: 'BUNDLE BUY',
    badgeType: 'solid-red',
    rating: 0,
    reviews: 0,
    price: 1199,
    originalPrice: 1399,
    savings: '$200 OFF^',
  },
];

export const TVS_PRODUCTS = [
  {
    id: 1,
    brand: 'LG',
    title: 'LG 55" OLED EVO AI C6 4K Smart TV [2026]',
    image: '/tp1.avif',
    badge: 'ON SALE',
    secondaryBadge: 'BUNDLE BUY',
    badgeType: 'solid-red',
    rating: 5.0,
    reviews: 5,
    price: 2345,
    originalPrice: 2945,
    savings: '$600 OFF^',
  },
  {
    id: 2,
    brand: 'BLAUPUNKT',
    title: 'Blaupunkt 55" 4K UHD LED Tizen Smart TV [2026]',
    image: '/tp2.avif',
    badge: 'ON SALE',
    badgeType: 'solid-red',
    rating: 0,
    reviews: 0,
    price: 449,
    originalPrice: 899,
    savings: '$450 OFF^',
  },
  {
    id: 3,
    brand: 'SAMSUNG',
    title: 'Samsung 65" R85H Micro RGB 4K Smart AI TV [2026]',
    image: '/tp3.avif',
    badge: 'ON SALE',
    badgeType: 'solid-red',
    rating: 4.6,
    reviews: 30,
    price: 1795,
    originalPrice: 2795,
    savings: '$1000 OFF^',
  },
  {
    id: 4,
    brand: 'LG',
    title: 'LG 75" QNED70B AI Mini-LED 4K Smart TV [2026]',
    image: '/tp4.avif',
    badge: 'ON SALE',
    badgeType: 'solid-red',
    rating: 4.0,
    reviews: 4,
    price: 1495,
    originalPrice: 1695,
    savings: '$200 OFF^',
    tagline: 'FREE DELIVERY',
  },
  {
    id: 5,
    brand: 'BLAUPUNKT',
    title: 'Blaupunkt 85" 4K UHD QLED Tizen Smart TV [2026]',
    image: '/tp5.avif',
    badge: 'ON SALE',
    badgeType: 'solid-red',
    rating: 0,
    reviews: 0,
    price: 899,
    originalPrice: 4899,
    savings: '$4000 OFF^',
  },
];

export const RECOMMENDATIONS = [
  {
    id: 1,
    brand: 'steelseries',
    title: 'SteelSeries Arctis Nova Pro Omni Gaming Headset (Black)',
    image: '/r1.avif',
    rating: 5.0,
    reviews: 1,
    price: 879,
  },
  {
    id: 2,
    title: 'Apple iPhone 17 Pro Max 256GB (Silver)',
    image: '/r2.avif',
    badge: 'TRADE IN YOUR OLD PHONE',
    badgeType: 'outline-red',
    rating: 4.7,
    reviews: 46,
    price: 1889,
    priceTagLabel: 'RED HOT DEAL',
  },
  {
    id: 3,
    title: 'Apple AirPods 4 with Active Noise Cancellation',
    image: '/r3.avif',
    badge: 'TRADE IN YOUR OLD AIRPODS',
    badgeType: 'outline-red',
    rating: 3.9,
    reviews: 101,
    price: 230,
    priceTagLabel: 'RED HOT DEAL',
  },
  {
    id: 4,
    title: 'Apple iPhone 17 Pro 256GB (Silver)',
    image: '/r2.avif',
    badge: 'TRADE IN YOUR OLD PHONE',
    badgeType: 'outline-red',
    rating: 4.2,
    reviews: 22,
    price: 1649,
    priceTagLabel: 'RED HOT DEAL',
  },
  {
    id: 5,
    title: 'Apple AirPods Pro 3',
    image: '/r5.avif',
    badge: 'TRADE IN YOUR OLD AIRPODS',
    badgeType: 'outline-red',
    rating: 3.9,
    reviews: 43,
    price: 330,
    priceTagLabel: 'RED HOT DEAL',
  }
];

export const NEW_PRODUCTS = [
  {
    id: 1,
    image: '/np1.webp',
    description: 'Mac mini. Little do-it-all.',
    button: 'Pre-order',
  },
  {
    id: 2,
    image: '/np2.webp',
    brand: 'Google',
    description: "Check out what's new from Google!",
    button: 'Shop now',
  },
  {
    id: 3,
    image: '/np3.webp',
    description: 'A playful new lineup of Pokémon Tonies is here!',
    button: 'Shop now',
    video: true,
  },
  {
    id: 4,
    image: '/np4.webp',
    description: 'Dream Sight & Dream Sock Duo!',
    button: 'Shop now',
    video: true,
  },
];

export const NEWS_TABS = [
  'Trending',
  'Tech',
  'Guides & Tips',
  'Music',
  'Games',
  'Movies',
];

export const NEWS_ITEMS = [
  {
    id: 1,
    image: '/n1.webp',
    title: 'Top gift ideas for dad!',
    large: true,
  },
  {
    id: 2,
    image: '/n1.webp',
    title: 'Your ultimate guide to electric shavers',
  },
  {
    id: 3,
    image: '/n3.webp',
    title: 'Pick the perfect beard trimmer',
  },
];

export const LATEST_TECH_PRODUCTS = [
  {
    id: 1,
    brand: 'Apple',
    title: 'Apple Mac Mini with M6 Chip, 12-core CPU/12-core GPU, 256GB/16GB',
    image: '/ltp1.webp',
    badge: 'PRE-ORDER',
    badge2: 'TRADE IN YOUR OLD COMPUTER',
    badgeType: 'purple',
    badgeType2: 'outline-red',
    price: 1449,
    buttonText: 'Pre-order',
  },
  {
    id: 2,
    brand: 'Apple',
    title: 'Apple Mac Studio with M5 Ultra Chip, 30-core CPU/64-core GPU, 1TB/96GB',
    image: '/ltp1.webp',
    badge: 'PRE-ORDER',
    badge2: 'TRADE IN YOUR OLD COMPUTER',
    badgeType: 'purple',
    badgeType2: 'outline-red',
    price: 9449,
    tagline: '+ DELIVERY FROM $9.99',
    buttonText: 'Pre-order',
  },
  {
    id: 3,
    brand: 'ASUS',
    title: 'ROG Xbox Ally X20 AMD Ryzen AI Z2 Extreme 24GB 1TB 120Hz Gaming Handheld (80Wh)',
    image: '/ltp3.avif',
    badge: 'PRE-ORDER',
    badgeType: 'purple',
    price: 2499,
    buttonText: 'Pre-order',
  },
  {
    id: 4,
    brand: 'ASUS',
    title: 'ROG XBOX Ally X20 Bundle',
    image: '/ltp3.avif',
    badge: 'PRE-ORDER',
    badgeType: 'purple',
    price: 4499,
    buttonText: 'Pre-order',
  },
  {
    id: 5,
    brand: 'Google',
    title: 'Google Pixel 11 5G 256GB (Frost)',
    image: '/ltp5.avif',
    badge: 'NEW AT JB!',
    badge2: 'TRADE IN YOUR OLD PHONE',
    badgeType: 'blue',
    badgeType2: 'outline-red',
    price: 1499,
    buttonText: 'Add to cart',
  },
];

export const SERVICES = [
  {
    id: 'installations',
    title: 'Installations',
    icon: Wrench,
  },
  {
    id: 'trade-in',
    title: 'Trade-in',
    icon: Smartphone,
  },
  {
    id: 'warranties',
    title: 'Extra Care warranties',
    icon: RotateCcw,
  },
  {
    id: 'extras',
    title: 'JB Hi-Fi Extras',
    icon: HandHeart,
  },
  {
    id: 'sim',
    title: 'Pre-Paid SIM',
    icon: Cpu,
  },
  {
    id: 'mobile-plans',
    title: 'Upfront mobile plans',
    icon: PhoneCall,
  },
  {
    id: 'broadband',
    title: 'Mobile broadband plans',
    icon: Wifi,
  },
  {
    id: 'byod',
    title: 'BYOD schools programs',
    icon: GraduationCap,
  },
];

export const BRANDS: BrandDataType[] = [
  { id: 'apple', name: 'Apple', logo: 'https://images.ctfassets.net/xa93kvziwaye/5FVTAmBSaX3q8wF61joQf6/c805197ae42988f2061e94205b8c4e1f/Brand_Card_Apple.png?fm=webp&f=top&fit=fill&q=75&w=384&h=231', href: '#' },
  { id: 'bose', name: 'Bose', logo: 'https://images.ctfassets.net/xa93kvziwaye/2gXuRCNt87LXk2FTUAJwKf/9789f3d255f2f18efe869bccbd5b9181/Brand_Card_Bose.png?fm=webp&f=top&fit=fill&q=75&w=384&h=231', href: '#' },
  { id: 'breville', name: 'Breville', logo: 'https://images.ctfassets.net/xa93kvziwaye/6Xi0lVZsks2Lg9IoANqIEK/00c0c9833637bbba704598d551ea91a9/Brand_Card_Breville.png?fm=webp&f=top&fit=fill&q=75&w=384&h=231', href: '#' },
  { id: 'dji', name: 'DJI', logo: 'https://images.ctfassets.net/xa93kvziwaye/5By6AbrQCStrSE6AHQpTLI/73481a33b0e82b751758f2608b0b4672/Brand_Card_DJI.png?fm=webp&f=top&fit=fill&q=75&w=384&h=231', href: '#' },
  { id: 'dyson', name: 'Dyson', logo: 'https://images.ctfassets.net/xa93kvziwaye/7smcBtOgYwZs5PKvhdyH6L/2bb7805f85b65f27cfbabe965f10ad25/Brand_Card_Dyson.png?fm=webp&f=top&fit=fill&q=75&w=384&h=231', href: '#' },
  { id: 'fisher-paykel', name: 'Fisher & Paykel', logo: 'https://images.ctfassets.net/xa93kvziwaye/ZGEPIUuKhIsv8LqNFMmAw/020a371a7131387f2947567de279569d/Brand_Card_Fisher___Paykel.png?fm=webp&f=top&fit=fill&q=75&w=384&h=231', href: '#' },
  { id: 'hisense', name: 'Hisense', logo: 'https://images.ctfassets.net/xa93kvziwaye/4B29pQIDHCRAWUNu5fOQNg/e6afd7f903e7ec63895c6f96e4a7c601/Hisense_Logo__1_.png?fm=webp&f=top&fit=fill&q=75&w=384&h=231', href: '#' },
  { id: 'google', name: 'Google', logo: 'https://images.ctfassets.net/xa93kvziwaye/73ePwGkDp4aM1zy6ioqtVL/7456ad41abd89946f077955ac5a9dba8/Brand_Card_Google.png?fm=webp&f=top&fit=fill&q=75&w=384&h=231', href: '#' },
  { id: 'hp', name: 'HP', logo: 'https://images.ctfassets.net/xa93kvziwaye/7zFrELUQbiCMMT0UicaDhI/972f0e2965fa290dcc87f900bc849157/Brand_Card_HP.png?fm=webp&f=top&fit=fill&q=75&w=384&h=231', href: '#' },
  { id: 'lg', name: 'LG', logo: 'https://images.ctfassets.net/xa93kvziwaye/54Cqnt3vlBcr1FLUvJNKcw/74b661f528eb60cbfee4a9e594909d9d/Brand_Card_LG.png?fm=webp&f=top&fit=fill&q=75&w=384&h=231', href: '#' },
];


export const SUSTAINABILITY_ITEMS: SustainabilityCardProps[] = [
  {
    id: 'sustainability',
    title: 'Sustainability',
    href: '#sustainability',
    image: 'https://images.ctfassets.net/xa93kvziwaye/cKcyHbLSlmaI9z7Rsu1Tr/0ab8bd106c2216f1a6333fa3a6e72abc/tile-sustainability.png?fm=webp&f=top&fit=fill&q=75&w=384&h=384',
  },
  {
    id: 'community',
    title: 'In the community',
    href: '#community',
    image: 'https://images.ctfassets.net/xa93kvziwaye/3DNodBThT900QBuUUtQiDd/4218697e83f489696f37e61e260297b8/tile-helping-hands.png?fm=webp&f=top&fit=fill&q=75&w=384&h=384',
  },
  {
    id: 'waste-reduction',
    title: 'Waste reduction and e-waste recycling',
    href: '#waste-reduction',
    image: 'https://images.ctfassets.net/xa93kvziwaye/1gXo3r70oJjRGd4U2SHaZb/56419090007dc3cb4e5e210858ab6394/tile-waste-reduction.png?fm=webp&f=top&fit=fill&q=75&w=384&h=384',
  },
  {
    id: 'climate-action',
    title: 'Progress on climate action',
    href: '#climate-action',
    image: 'https://images.ctfassets.net/xa93kvziwaye/4pDqokBGJEkEBVAGHsi8Hq/936ba50dc15558c60e59b25471359cfc/tile-climate-action.png?fm=webp&f=top&fit=fill&q=75&w=384&h=384',
  },
  {
    id: 'ethical-sourcing',
    title: 'Ethical sourcing',
    href: '#ethical-sourcing',
    image: 'https://images.ctfassets.net/xa93kvziwaye/SOgK9XKz3ZZx8CVZ8S3H6/efac1642b16a9cff9c5499c1cfeedb09/tile-ethical-sourcing.png?fm=webp&f=top&fit=fill&q=75&w=384&h=384',
  },
  {
    id: 'carbon-neutral',
    title: 'Carbon Neutral tree planting partnership',
    href: '#carbon-neutral',
    image: 'https://images.ctfassets.net/xa93kvziwaye/46bXx0SBIE2aOK2f5iBZlS/c84e056faa929d2de095fbaed3f70abe/tile-carbon-neutral-partnership.png?fm=webp&f=top&fit=fill&q=75&w=384&h=384',
  },
];

export const FEATURED_PRODUCTS: ProductDataType[] = [
  {
    id: 1,
    brand: 'Insta360',
    title: 'Insta360 X6 8K 360 Action Camera Essentials Bundle (Midnight Black)',
    image: '/c5.webp',
    badge: 'NEW AT JB!',
    badgeType: 'blue',
    rating: 5.0,
    reviews: 2,
    price: 1159,
  },
  {
    id: 2,
    brand: 'DJI',
    title: 'DJI Lito 1 4K Drone Fly More Combo (DJI RC-N3)',
    image: '/c5.webp',
    price: 779,
  },
  {
    id: 3,
    brand: 'Insta360',
    title: 'Insta360 Luna Ultra Ultra 8K Gimbal Camera Creator Bundle (Cosmic Black)',
    image: '/c5.webp',
    badge: 'ON SALE',
    badgeType: 'solid-red',
    rating: 5.0,
    reviews: 3,
    price: 1398,
    originalPrice: 1549,
    savings: '$151 OFF^',
  },
  {
    id: 4,
    brand: 'DJI',
    title: 'DJI Osmo Pocket 4 Creator Combo',
    image: '/c5.webp',
    rating: 4.7,
    reviews: 3,
    price: 959,
  },
];

export const COLLECTION_PRODUCTS: ProductDataType[] = [
  {
    id: 1,
    brand: 'DJI',
    title: 'DJI Osmo Action 5 Pro Standard Combo',
    image: '/c5.webp',
    badge: 'ON SALE',
    badgeType: 'solid-red',
    rating: 5.0,
    reviews: 5,
    price: 399,
    originalPrice: 459,
    savings: '$60 OFF^',
  },
  {
    id: 2,
    brand: 'DJI',
    title: 'DJI Osmo Pocket 4 Creator Combo',
    image: '/c5.webp',
    rating: 4.7,
    reviews: 3,
    price: 959,
  },
  {
    id: 3,
    brand: 'DJI',
    title: 'DJI Lito X1 4K Drone Fly More Combo (DJI RC 2)',
    image: '/c5.webp',
    rating: 5.0,
    reviews: 2,
    price: 1069,
  },
  {
    id: 4,
    brand: 'Camp Snap',
    title: 'Camp Snap Pro Digital Camera',
    image: '/c5.webp',
    badge: 'JB EXCLUSIVE',
    badgeType: 'purple', // Style configured in ProductCard for yellow-on-black/purple badges
    rating: 4.7,
    reviews: 15,
    price: 168,
    originalPrice: 199,
    savings: '$31 OFF^',
  },
  {
    id: 5,
    brand: 'DJI',
    title: 'DJI Osmo Pocket 3 4K 3 Axis Gimbal Camera',
    image: '/c5.webp',
    rating: 4.1,
    reviews: 15,
    price: 599,
  },
  {
    id: 6,
    brand: 'DJI',
    title: 'DJI Osmo Pocket 4P Vlog Combo',
    image: '/c5.webp',
    rating: 2.5,
    reviews: 8,
    price: 1099,
  },
  {
    id: 7,
    brand: 'SONY',
    title: 'Sony CyberShot ZV-1F 4K Vlog Camera (Black)',
    image: '/c5.webp',
    badge: 'ON SALE',
    badgeType: 'solid-red',
    secondaryBadge: 'BUNDLE BUY',
    rating: 4.5,
    reviews: 23,
    price: 697,
    originalPrice: 749,
    savings: '$52 OFF^',
  },
  {
    id: 8,
    brand: 'GoPro',
    title: 'GoPro Hero13 Black 5.3K HyperSmooth 6.0 Action Cam',
    image: '/c5.webp',
    badge: 'ON SALE',
    badgeType: 'solid-red',
    rating: 3.3,
    reviews: 73,
    price: 474,
    originalPrice: 644,
    savings: '$170 OFF^',
  },
];